=== Wyrmheart-Team/Dragon_Mounts_Remastered/src/main/resources/data/dmr/schemas/types/breed_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "schemas/types/breed_schema.json",
  "$version": "1.0.0",
  "$comment": "This schema is used to validate dragon breed JSON files in the data/dmr/breeds directory. Each breed defines a type of dragon with its own characteristics, abilities, and behaviors.",
  "title": "Dragon Breed Schema",
  "description": "Schema for defining dragon breeds with their characteristics, abilities, and behaviors",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "ambient_sound": {
      "$ref": "../definitions/resources.json#/$defs/sound",
      "description": "Ambient sound played by the dragon during normal activity. Should be a valid sound resource identifier.",
      "examples": ["dmr:entity.dragon.breathe", "minecraft:entity.ender_dragon.growl"]
    },
    "death_loot": {
      "$ref": "../definitions/resources.json#/$defs/loot_table",
      "description": "Loot table that determines what items drop when the dragon dies. Should be a valid loot table resource identifier.",
      "examples": ["dmr:entities/dragon/fire", "minecraft:entities/ender_dragon"]
    },
    "hatch_time": {
      "$ref": "../definitions/attributes.json#/$defs/duration_integer",
      "description": "Time in ticks required for a dragon egg to hatch. If not specified, the default value from server configuration will be used.",
      "examples": [12000, 24000]
    },
    "growth_time": {
      "$ref": "../definitions/attributes.json#/$defs/duration_integer",
      "description": "Time in ticks required for a baby dragon to grow into an adult. If not specified, the default value from server configuration will be used.",
      "examples": [72000, 144000]
    },
    "size_modifier": {
      "type": "number",
      "description": "Size multiplier applied to the dragon's base dimensions. Values greater than 1.0 make the dragon larger, while values less than 1.0 make it smaller.",
      "minimum": 0,
      "default": 1.0,
      "examples": [0.8, 1.2]
    },
    "primary_color": {
      "$ref": "../definitions/resources.json#/$defs/color",
      "description": "Primary color of the dragon in hexadecimal format (without # prefix). Used primarily for coloring spawn eggs and some minor visual effects.",
      "examples": ["912400", "161616", "62ff"]
    },
    "secondary_color": {
      "$ref": "../definitions/resources.json#/$defs/color",
      "description": "Secondary color of the dragon in hexadecimal format (without # prefix). Used primarily for coloring spawn eggs and some minor visual effects.",
      "examples": ["ff9819", "ff63e8", "5999ff"]
    },
    "inventory_texture": {
      "$ref": "../definitions/resources.json#/$defs/texture",
      "description": "The texture displayed in the dragon's inventory UI. Should be a valid texture resource identifier.",
      "examples": ["minecraft:textures/block/magma.png", "textures/block/obsidian.png"]
    },
    "immunities": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "Damage type that the dragon is immune to. Common values include 'onFire', 'inFire', 'lava', 'drown', 'hotFloor', and 'dragonBreath'.",
        "pattern": "^[a-zA-Z0-9_]+$"
      },
      "description": "List of damage types that the dragon is immune to. Dragons with these immunities will not take damage from the specified sources.",
      "examples": [["onFire", "inFire", "lava", "hotFloor"], ["drown"]],
      "minItems": 1
    },
    "attributes": {
      "$ref": "../definitions/attributes.json#/$defs/attributes",
      "description": "Base attributes of the dragon that affect its stats like health, speed, armor, etc. Maps attribute IDs to their numeric values.",
      "examples": [
        {"minecraft:generic.max_health": 75.0, "minecraft:generic.armor": 8.0}
      ]
    },
    "habitats": {
      "type": "array",
      "items": {
        "$ref": "habitat_schema.json",
        "description": "Habitat definition that specifies where the dragon prefers to live. Different habitat types include biome, fluid, height, light, and more."
      },
      "description": "List of habitats where the dragon prefers to live. These affect breeding, spawning, and other behaviors.",
      "minItems": 1,
      "examples": [
        [
          {"type": "biome", "biome_tag": "minecraft:is_end"},
          {"type": "nearby_blocks", "block_tag": "dmr:end_dragon_habitat_blocks"}
        ]
      ]
    },
    "abilities": {
      "type": "array",
      "items": {
        "$ref": "../definitions/abilities.json#/$defs/ability_entry",
        "description": "Ability entry that specifies an ability and the chance of a dragon having it."
      },
      "description": "List of possible abilities that the dragon can have, along with the chance of each ability occurring.",
      "minItems": 1,
      "examples": [
        [
          {"ability": "ember_aura", "chance": 0.5},
          {"ability": "fire_proof", "chance": 0.5}
        ]
      ]
    },
    "breath_type": {
      "$ref": "../definitions/abilities.json#/$defs/breath_type",
      "description": "The type of breath attack that the dragon uses. Should reference a valid breath type defined in a breath type JSON file.",
      "examples": ["fire", "ender", "water"]
    },
    "taming_items": {
      "type": "array",
      "items": {
        "$ref": "../definitions/resources.json#/$defs/item",
        "description": "Item that can be used to tame this dragon breed. Should be a valid item identifier."
      },
      "description": "List of items that can be used to tame this dragon breed. Players must use one of these items to tame a wild dragon.",
      "examples": [["minecraft:blaze_powder", "minecraft:fire_charge"]],
      "minItems": 1
    },
    "breeding_items": {
      "type": "array",
      "items": {
        "$ref": "../definitions/resources.json#/$defs/item",
        "description": "Item that can be used to breed this dragon. Should be a valid item identifier."
      },
      "description": "List of items that can be used to breed this dragon with another dragon. Players must use one of these items to initiate breeding.",
      "examples": [["minecraft:golden_apple", "minecraft:enchanted_golden_apple"]],
      "minItems": 1
    },
    "hatch_particles": {
      "$ref": "../definitions/resources.json#/$defs/particle",
      "description": "Particle effect displayed when a dragon egg of this breed hatches. Should be a valid particle effect identifier.",
      "examples": ["minecraft:flame", "minecraft:portal", "minecraft:end_rod"]
    },
    "accessories": {
      "type": "array",
      "items": {
        "$ref": "../definitions/resources.json#/$defs/identifier",
        "description": "Accessory identifier for visual elements on the dragon model, such as horns, fins, or scales."
      },
      "description": "List of accessories that appear on this dragon breed. These are visual elements that distinguish different breeds.",
      "examples": [["middle_tail_scales", "tail_horns"], ["second_horns", "tail_mem"]],
      "minItems": 1
    },
    "loot_tables": {
      "$ref": "../definitions/resources.json#/$defs/loot_tables",
      "description": "Collection of loot tables that can be dropped by this dragon breed, along with their drop chances and quantities.",
      "examples": [
        [
          {
            "table": "minecraft:chests/desert_pyramid",
            "chance": 0.065,
            "min": 1,
            "max": 1
          }
        ]
      ]
    },
    "model_location": {
      "$ref": "../definitions/resources.json#/$defs/model",
      "description": "Resource location of the 3D model file for this dragon breed. Should be a valid model file path.",
      "examples": ["dmr:geo/dragon.geo.json"]
    },
    "animation_location": {
      "$ref": "../definitions/resources.json#/$defs/animation",
      "description": "Resource location of the animation file for this dragon breed. Should be a valid animation file path.",
      "examples": ["dmr:animations/dragon.animation.json"]
    },
    "variants": {
      "type": "array",
      "items": {
        "$ref": "variant_schema.json",
        "description": "Variant definition for this dragon breed. Variants are visual or behavioral variations within a breed."
      },
      "description": "List of variants available for this dragon breed. Variants can have different textures, colors, and other properties.",
      "minItems": 1,
      "examples": [
        [
          {
            "id": "albino",
            "texture": "dmr:textures/entity/dragon/albino.png",
            "primary_color": "ffffff",
            "secondary_color": "eeeeee"
          }
        ]
      ]
    },
    "armor_type": {
      "type": "string",
      "description": "The armor type ID that this dragon breed uses. References an armor type defined in an armor JSON file.",
      "default": "default",
      "examples": ["default", "heavy", "light"]
    }
  },
  "required": ["primary_color", "secondary_color"]
}

=== Wyrmheart-Team/Dragon_Mounts_Remastered/src/test/resources/data/dmr/breeds/test2.json
{
  "hatch_particles": "minecraft:end_rod",
  "accessories": ["middle_tail_scales"],
  "abilities": [
    {
      "ability": "gem_guard",
      "chance": 0.5
    },
    {
      "ability": "crystal_harmony",
      "chance": 0.5
    }
  ],
  "primary_color": "10975729",
  "secondary_color": "16698599",
  "ambient_sound": "dmr:entity.dragon.breathe",
  "growth_time": 72000,
  "hatch_time": 12000,
  "loot_tables": [
    {
      "table": "minecraft:chests/stronghold_library",
      "chance": 0.15,
      "min": 1,
      "max": 1
    }
  ]
}

=== Wyrmheart-Team/Dragon_Mounts_Remastered/src/test/resources/data/dmr/breeds/ice_test.json
{
  "hatch_particles": "minecraft:snowflake",
  "immunities": ["freeze"],
  "abilities": [
    {
      "ability": "frost_walker",
      "chance": 1.0
    },
    {
      "ability": "crystal_harmony",
      "chance": 0.6
    }
  ],
  "primary_color": "87ceeb",
  "secondary_color": "b0e0e6",
  "ambient_sound": "minecraft:block.glass.break",
  "growth_time": 52000,
  "hatch_time": 9000,
  "accessories": ["second_horns", "middle_tail_scales"],
  "breath_type": "ice",
  "loot_tables": [
    {
      "table": "minecraft:chests/igloo_chest",
      "chance": 0.15,
      "min": 1,
      "max": 1
    }
  ]
}

=== Wyrmheart-Team/Dragon_Mounts_Remastered/src/test/resources/data/dmr/breeds/water_test.json
{
  "hatch_particles": "minecraft:dripping_water",
  "immunities": ["drown"],
  "abilities": [
    {
      "ability": "aquatic_grace",
      "chance": 1.0
    },
    {
      "ability": "swift_swim",
      "chance": 1.0
    }
  ],
  "primary_color": "0080ff",
  "secondary_color": "4169e1",
  "ambient_sound": "minecraft:block.water.ambient",
  "growth_time": 45000,
  "hatch_time": 7500,
  "accessories": ["leg_fins", "tail_mem"],
  "breath_type": "water",
  "loot_tables": [
    {
      "table": "minecraft:chests/buried_treasure",
      "chance": 0.25,
      "min": 1,
      "max": 2
    }
  ]
}

=== Wyrmheart-Team/Dragon_Mounts_Remastered/src/main/resources/data/dmr/dmr/breeds/fire.json
{
  "abilities": [
    "ember_aura",
    "fire_proof"
  ],
  "habitats": [
    {
      "type": "nearby_blocks",
      "block_tag": "dmr:fire_dragon_habitat_blocks"
    },
    {
      "type": "in_fluid",
      "fluid_tag": "minecraft:lava",
      "point_multiplier": 3.0
    },
    {
      "type": "world_height",
      "height": 10,
      "below": true
    }
  ],
  "hatch_particles": "minecraft:flame",
  "immunities": [
    "onFire",
    "inFire",
    "lava",
    "hotFloor"
  ],
  "primary_color": "912400",
  "secondary_color": "ff9819",
  "loot_tables": [
    {
      "table": "minecraft:chests/desert_pyramid",
      "chance": 0.085,
      "min": 1,
      "max": 1
    }
  ],
  "accessories": [
    "middle_tail_scales"
  ]
}

=== Wyrmheart-Team/Dragon_Mounts_Remastered/src/main/resources/data/dmr/dmr/breeds/forest.json
{
  "abilities": [
    "nature_blessing",
    "camouflage"
  ],
  "habitats": [
    {
      "type": "nearby_blocks",
      "block_tag": "dmr:forest_dragon_habitat_blocks"
    },
    {
      "type": "biome",
      "biome_tag": "minecraft:is_jungle"
    },
    {
      "type": "biome",
      "biome_tag": "minecraft:is_forest"
    }
  ],
  "hatch_particles": "minecraft:happy_villager",
  "primary_color": "54a00",
  "secondary_color": "a9600",
  "loot_tables": [
    {
      "table": "minecraft:chests/jungle_temple",
      "chance": 0.3,
      "min": 1,
      "max": 1
    }
  ]
}

=== Wyrmheart-Team/Dragon_Mounts_Remastered/src/test/resources/data/dmr/dmr/breeds/test2.json
{
  "hatch_particles": {
    "type": "minecraft:end_rod"
  },
  "accessories": ["middle_tail_scales"],
  "habitats": [
    {
      "type": "nearby_blocks",
      "block_tag": "dmr:amethyst_dragon_habitat_blocks"
    }
  ],
  "abilities": [
    {
      "type": "gem_guard"
    },
    {
      "type": "crystal_harmony"
    }
  ],
  "primary_color": 10975729,
  "secondary_color": 16698599,
  "ambient_sound": "dmr:entity.dragon.breathe",
  "growth_time": 72000,
  "hatch_time": 12000,
  "loot_tables": [
    {
      "table": "minecraft:chests/stronghold_library",
      "chance": 0.15,
      "min": 1,
      "max": 1
    }
  ]
}

=== Wyrmheart-Team/Dragon_Mounts_Remastered/src/main/resources/data/dmr/breeds/amethyst.json
{
  "hatch_particles": "minecraft:end_rod",
  "accessories": ["middle_tail_scales"],
  "habitats": [
    {
      "type": "nearby_blocks",
      "block_tag": "dmr:amethyst_dragon_habitat_blocks"
    }
  ],
  "abilities": [
    {
      "ability": "#common_abilities"
    },
    {
      "ability": "gem_guard",
      "chance": 0.5
    },
    {
      "ability": "crystal_harmony",
      "chance": 0.5
    }
  ],
  "primary_color": "A779F1",
  "secondary_color": "FECCE7",
  "ambient_sound": "dmr:entity.dragon.breathe",
  "breath_type": "amethyst",
  "inventory_texture": "textures/block/amethyst_block.png",
  "loot_tables": [
    {
      "table": "minecraft:chests/stronghold_library",
      "chance": 0.1,
      "min": 1,
      "max": 1
    }
  ]
}

=== Wyrmheart-Team/Dragon_Mounts_Remastered/src/main/resources/data/dmr/dmr/breeds/water.json
{
  "habitats": [
    {
      "type": "in_fluid",
      "fluid_tag": "minecraft:water",
      "point_multiplier": 3.0
    },
    {
      "type": "nearby_blocks",
      "block_tag": "dmr:water_dragon_habitat_blocks"
    },
    {
      "type": "biome",
      "biome_tag": "minecraft:is_ocean"
    },
    {
      "type": "biome",
      "biome_tag": "minecraft:is_river"
    },
    {
      "type": "biome",
      "biome_tag": "minecraft:is_beach"
    }
  ],
  "hatch_particles": "minecraft:dripping_water",
  "immunities": ["drown"],
  "abilities": ["aquatic_grace", "swift_swim"],
  "primary_color": "62ff",
  "secondary_color": "5999ff",
  "loot_tables": [
    {
      "table": "minecraft:chests/buried_treasure",
      "chance": 0.175,
      "min": 1,
      "max": 1
    }
  ],
  "accessories": ["tail_horns", "leg_fins"]
}
